version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: "Europe/Warsaw"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: me.clip:placeholderapi
    versions:
    - "> 2.10.9"

